# Site settings
title: Jingshuo's homepage
baseurl: "/ap"
url: "https://seanzliu.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Jingshuo Liu
  desc: Nice to meet you.
  email: jingshuoliu@stu.hit.edu.cn
  selfie: assets/img/profile.png

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: SeanZLiu
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.cn/incareer/in/璟烁-刘-694329218
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: 
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
